export const LoaderMessage = {
    Start: "loader:start",
    PauseGame: "loader:pauseGame",
    ResumeGame: "loader:resumeGame",
    StopGame: "loader:stopGame",
    SendEvents: "loader:sendEvents",
    SetExecutionMode: "loader:setExecutionMode",
    TargetTime: "loader:targetTime",
    SetReplayOriginDate: "loader:setReplayOriginDate",
    SetScale: "loader:setScale",
    SetMasterVolume: "loader:setMasterVolume",
    GetGameVars: "loader:getGameVars",
    ChangeDriverState: "loader:changeDriverState",
    ResetSurface: "loader:resetSurface",
    SetTabIndex: "loader:setTabIndex",
    GameCreated: "loader:gameCreated",
    Error: "loader:error",
    PlayOriginDate: "loader:playOriginDate",
    AcquireAMFlow: "loader:acquireAMFlow",
    ReleaseAMFlow: "loader:releaseAMFlow",
    ExternalSend: "loader:externalSend",
    External: "loader:external",
    SkippingChanged: "loader:skippingChanged",
    GameLoaded: "loader:gameLoaded",
    GameStarted: "loader:gameStarted",
} as const;
